name: Build LMS Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      # Remove NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g vitest
        
      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test
        
      - name: Build project
        run: npm run build

      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
            build
            dist
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Check build status
        if: failure()
        run: |
          echo "Build failed!"
          exit 1